[2024-09-13T09:13:44.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-13T09:13:44.752+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launch_dag.get_pictures manual__2024-09-13T09:13:39.507776+00:00 [queued]>
[2024-09-13T09:13:44.758+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launch_dag.get_pictures manual__2024-09-13T09:13:39.507776+00:00 [queued]>
[2024-09-13T09:13:44.759+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-13T09:13:44.766+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_pictures> on 2024-09-13 09:13:39.507776+00:00
[2024-09-13T09:13:44.772+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-13T09:13:44.773+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2024-09-13T09:13:44.774+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launch_dag', 'get_pictures', 'manual__2024-09-13T09:13:39.507776+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/download_rocket_launch.py', '--cfg-path', '/tmp/tmpozrn24sq']
[2024-09-13T09:13:44.774+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask get_pictures
[2024-09-13T09:13:44.822+0000] {task_command.py:467} INFO - Running <TaskInstance: download_rocket_launch_dag.get_pictures manual__2024-09-13T09:13:39.507776+00:00 [running]> on host 28bc5394dfc7
[2024-09-13T09:13:44.878+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_rocket_launch_dag' AIRFLOW_CTX_TASK_ID='get_pictures' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T09:13:39.507776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-13T09:13:39.507776+00:00'
[2024-09-13T09:13:44.879+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-13T09:13:44.880+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-13T09:13:44.881+0000] {logging_mixin.py:190} INFO - Current task name:get_pictures state:running start_date:2024-09-13 09:13:44.753558+00:00
[2024-09-13T09:13:44.882+0000] {logging_mixin.py:190} INFO - Dag name:download_rocket_launch_dag and current dag run status:running
[2024-09-13T09:13:44.883+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-13T09:13:44.886+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/download_rocket_launch.py", line 28, in _get_pictures
    with open("/output/launches.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/output/launches.json'
[2024-09-13T09:13:44.900+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-13T09:13:44.901+0000] {logging_mixin.py:190} INFO - Task start:2024-09-13 09:13:44.753558+00:00 end:2024-09-13 09:13:44.899914+00:00 duration:0.146356
[2024-09-13T09:13:44.902+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_pictures> dag:<DAG: download_rocket_launch_dag> dagrun:<DagRun download_rocket_launch_dag @ 2024-09-13 09:13:39.507776+00:00: manual__2024-09-13T09:13:39.507776+00:00, state:running, queued_at: 2024-09-13 09:13:39.519873+00:00. externally triggered: True>
[2024-09-13T09:13:44.902+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/output/launches.json'
[2024-09-13T09:13:44.903+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=download_rocket_launch_dag, task_id=get_pictures, run_id=manual__2024-09-13T09:13:39.507776+00:00, execution_date=20240913T091339, start_date=20240913T091344, end_date=20240913T091344
[2024-09-13T09:13:44.914+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-13T09:13:44.921+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task get_pictures ([Errno 2] No such file or directory: '/output/launches.json'; 86)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/download_rocket_launch.py", line 28, in _get_pictures
    with open("/output/launches.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/output/launches.json'
[2024-09-13T09:13:44.947+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-13T09:13:44.974+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-13T09:13:44.977+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
